---
- name: Install OS packages.
  package:
    name:
      - python3
      - python3-dev
      - python3-venv
      - libaugeas0
      - python3-pip

- name: Create virtual environment
  command: "python3 -m venv {{ certbot_dir }}"
  args:
    creates: "{{ certbot_dir }}"

- name: Install pip requirements.
  pip:
    name: "{{ certbot_pip_packages }}"
    virtualenv: "{{ certbot_dir }}"

- name: Set certbot script
  set_fact:
    certbot_script: "{{ certbot_dir }}/bin/certbot"